# Generated by Django 3.0.5 on 2024-09-17 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_auto_20240917_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
