# Generated by Django 3.0.5 on 2024-09-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0011_auto_20240918_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='class_id',
            field=models.IntegerField(unique=True),
        ),
    ]
