# Generated by Django 3.0.5 on 2024-11-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_auto_20240918_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_pic/CustomerProfilePic/'),
        ),
    ]
